DROP TABLE CardPercentage
GO

CREATE TABLE CardPercentage
(
	CardPercentageId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CardId INTEGER NOT NULL,
	PercentageType TINYINT NOT NULL,
	GenerationPercentage FLOAT NOT NULL,
	GenerationRatePer2048 SMALLINT NOT NULL,
	CONSTRAINT FK_CardPercentage_Card FOREIGN KEY (CardId) 
		REFERENCES Card (CardId) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_CardPercentage_PercentageType FOREIGN KEY (PercentageType) 
		REFERENCES C_PercentageType (PercentageTypeCode) ON DELETE NO ACTION ON UPDATE NO ACTION
)