DROP TABLE Equippable
GO

CREATE TABLE Equippable
(
	EquippableId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	TargetCardId INTEGER NOT NULL,
	EquipCardId INTEGER NOT NULL,
	CONSTRAINT FK_Equippable_TargetCard FOREIGN KEY (TargetCardId) 
		REFERENCES Card (CardId) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_Equippable_EquipCard FOREIGN KEY (EquipCardId) 
		REFERENCES Card (CardId) ON DELETE NO ACTION ON UPDATE NO ACTION
)