DROP TABLE SecondaryType
GO

CREATE TABLE SecondaryType
(
	SecondaryTypeId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CardId INTEGER NOT NULL,
	MonsterType TINYINT NOT NULL,
	CONSTRAINT FK_SecondaryType_Card FOREIGN KEY (CardId) 
		REFERENCES Card (CardId) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_SecondaryType_MonsterType FOREIGN KEY (MonsterType) 
		REFERENCES C_MonsterType (MonsterTypeCode) ON DELETE NO ACTION ON UPDATE NO ACTION
)